from __future__ import annotations

import hashlib
import json
import sys
import tempfile
import unittest
from pathlib import Path

SKILL_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(SKILL_ROOT))

from scripts.helpers import build_pages, compute_coverage
from scripts.ingest_document import _remove_stale_generated, run_ingest
from scripts.recovery import build_recovery_report, record_attempt
from scripts.contracts import validate_contract


class ExtractionV2Tests(unittest.TestCase):
    def test_confirmed_nontext_pages_are_not_confused_with_unknown_or_unreadable(self) -> None:
        reviewed = {
            1: {"outcome": "blank", "semantic_description": "Página integralmente em branco.", "description_source": "human_review"},
            2: {"outcome": "image_only", "semantic_description": "Fotografia de fachada sem texto visível.", "description_source": "vision_model"},
        }
        rendered = {n: {"validated": True, "created": True} for n in (1, 2)}
        pages, _ = build_pages(["", ""], source_kind=".pdf", render_by_page=rendered,
                               page_descriptions=reviewed, vision_provider="agent_review")
        coverage = compute_coverage(pages, 2)
        self.assertEqual([page.status for page in pages], ["COMPLETE", "COMPLETE"])
        self.assertEqual([page.quality for page in pages], ["nontext_confirmed", "nontext_confirmed"])
        self.assertEqual(coverage["pages_confirmed_blank"], 1)
        self.assertEqual(coverage["pages_image_only"], 1)
        self.assertEqual(coverage["pages_unknown_content"], 0)
        self.assertTrue(coverage["full_conversion_complete"])

        unknown, _ = build_pages([""], source_kind=".pdf", render_by_page={1: rendered[1]})
        unreadable, _ = build_pages(
            [""], source_kind=".pdf", render_by_page={1: rendered[1]},
            page_descriptions={1: {"outcome": "unreadable", "description_source": "human_review"}},
        )
        self.assertEqual(compute_coverage(unknown, 1)["pages_unknown_content"], 1)
        self.assertEqual(compute_coverage(unreadable, 1)["pages_unreadable"], 1)
        self.assertEqual(unknown[0].status, "PARTIAL")
        self.assertEqual(unreadable[0].status, "PARTIAL")
        self.assertFalse(compute_coverage(unreadable, 1)["full_conversion_complete"])

    def test_recovery_queue_only_records_observed_actions_and_bounds_retries(self) -> None:
        pages, _ = build_pages([""], source_kind=".pdf", vision_provider="agent_review")
        pages[0].source_sha256 = "a" * 64
        report = build_recovery_report(pages, "a" * 64)
        codes = {finding["code"] for finding in report["findings"]}
        self.assertEqual(codes, {"PAGE_CONTENT_UNKNOWN", "PAGE_RENDER_MISSING", "PAGE_VISION_PENDING"})
        self.assertEqual({attempt["action"] for attempt in report["attempts"]}, {"extract_text"})
        self.assertFalse(pages[0].vision["attempted"])
        finding_id = report["findings"][0]["id"]
        for index in range(3):
            report = record_attempt(report, finding_id, "inspect_page", f"bytes-{index}", "no_readable_text", f"image-{index}.png")
        with self.assertRaisesRegex(ValueError, "mesma ação"):
            record_attempt(report, finding_id, "inspect_page", "bytes-2", "no_readable_text", "same")
        with self.assertRaisesRegex(ValueError, "Limite"):
            record_attempt(report, finding_id, "inspect_page", "bytes-3", "no_readable_text", "new")

    def test_cleanup_preserves_untracked_input_and_changed_generated_file(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            output = Path(directory)
            (output / "images").mkdir()
            generated = output / "images" / "old.png"
            generated.write_bytes(b"old generated bytes")
            uploaded = output / "images" / "uploaded.png"
            uploaded.write_bytes(b"user supplied bytes")
            changed = output / "legal_review.json"
            changed.write_bytes(b"new user review")
            old_hash = hashlib.sha256(b"old generated bytes").hexdigest()
            previous = {"artifact_hashes": {"images/old.png": old_hash,
                                            "legal_review.json": hashlib.sha256(b"previous generated review").hexdigest()}}
            _remove_stale_generated(output, {"images/", "legal_review.json"}, previous, [uploaded])
            self.assertFalse(generated.exists())
            self.assertEqual(uploaded.read_bytes(), b"user supplied bytes")
            self.assertEqual(changed.read_bytes(), b"new user review")

    def test_ingest_emits_recovery_artifact_and_observed_runtime(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / "processo.txt"
            source.write_text("A autora prestou serviços em 2024.", encoding="utf-8")
            output = root / "out"
            manifest = run_ingest(source, output)["manifest"]
            self.assertEqual(manifest["recovery"]["status"], "completed")
            self.assertTrue((output / "recovery_findings.json").is_file())
            self.assertGreaterEqual(manifest["execution_metrics"]["elapsed_seconds"], 0)
            self.assertIn("recovery_findings.json", manifest["artifact_hashes"])
            recovery = json.loads((output / "recovery_findings.json").read_text(encoding="utf-8"))
            self.assertEqual(validate_contract(recovery, "recovery_findings.schema.json"), [])


if __name__ == "__main__":
    unittest.main()
